import styles from './Cocktail.module.scss'
import { useState } from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link'
import DetailView from '../../components/detailView/detailView'
import Head from 'next/head'
import Image from 'next/image'


export default function Cocktail() {
  const router = useRouter();
  const data = router.query;
  const [id, setId] = useState(Date.now())
  const handleClick = (e) => {
    setId(Date.now())
  }
  return(
    <>
      <Head>
        <title>Order This!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Enriqueta:wght@400;500;600;700&display=swap" rel="stylesheet"/>
      </Head>
      <Link href="/">
        <button className={styles.homebutton}>Home</button>
      </Link>
      <div className={styles.mainbox}>
        <DetailView data={data} key={id}/>
        <div className={styles.actionBox}>
          <button onClick={ e => handleClick(e)}className={`${styles.button} ${styles.buttonLeft}`}>Give Me Another!</button>
        <Link href='/drinkPreference/form'>
          <button className={`${styles.button} ${styles.buttonRight}`}>Actually I Have Some Preferences</button>
        </Link>
        </div>
      </div>
    </>
  )
}
