import React from 'react'

export const flavors = {
  Grapefruit: {state:false, names: ['Grapefruit juice', 'grapefruit']},
  "Lime": {state: false, names:['Lime juice', 'lime']},
  Strawberry:{state: false, names:['strawberries', 'strawberry syrup']},
  Lemon:{state: false, names: ['lemonade', 'lemon']},
  "Chocolate":{state: false, names: ['chocolate','chocolate liqueur']},
  "Coffee Liqueur":{state: false, names: ['coffee','kahlua', 'coffee liqueur']},
  "Apple":{state: false, names: ['apple juice', 'applejack']},
  "Peach":{state: false, names: ['peach schnapps']},
  "Ginger":{state: false, names: ['ginger ale']},
  "Cranberry":{state: false, names: ['cranberry juice']},
  "Tomato":{state: false, names: ['tomato juice']},
  "Raspberry":{state: false, names: ['raspberry syrup']},
  "Almond":{state: false, names: ['amaretto']},
  "Orange":{state: false, names: ['orange juice', 'cointreau', 'triple sec', 'grand marnier']},
  "Pineapple":{state: false, names: ['pineapple juice', 'pineapple']},
  "Mint":{state: false, names: ['mint', 'creme de menthe']},
  "Banana":{state: false, names: ['banana', 'banana liqueur']},
  vanilla: {state: false, names: ['vanilla', 'cream']},
  "Cherry":{state: false, names: ['cherry', 'cherry juice', 'brandy']},
  "Coconut": {state: false, names: ['coconut cream', 'coconut liqueur']},
  "Anise": {state: false, names:['Sambuca', 'absinthe'],
}
